<?php

namespace Database\Factories;

use App\Models\Obat;
use Illuminate\Database\Eloquent\Factories\Factory;

class ObatFactory extends Factory
{
    protected $model = Obat::class;

    private static $index = 0;

    private static $obatList = [
        ['Paracetamol', 5000, 'tablet', 'Pereda nyeri dan demam'],
        ['Ibuprofen', 8000, 'tablet', 'Anti inflamasi'],
        ['Amoxicillin', 12000, 'kapsul', 'Antibiotik'],
        ['Cefadroxil', 15000, 'kapsul', 'Antibiotik golongan sefalosporin'],
        ['Metformin', 10000, 'tablet', 'Obat diabetes tipe 2'],
        ['Amlodipine', 12000, 'tablet', 'Obat hipertensi'],
        ['Captopril', 8000, 'tablet', 'Obat hipertensi'],
        ['Omeprazole', 15000, 'kapsul', 'Obat maag dan asam lambung'],
        ['Ranitidine', 10000, 'tablet', 'Obat maag'],
        ['Antasida DOEN', 12000, 'tablet', 'Obat maag'],
        ['Domperidone', 10000, 'tablet', 'Obat mual dan muntah'],
        ['Ondansetron', 18000, 'tablet', 'Obat mual'],
        ['Salbutamol', 10000, 'tablet', 'Obat asma'],
        ['Dexamethasone', 8000, 'tablet', 'Kortikosteroid anti inflamasi'],
        ['Prednisone', 7000, 'tablet', 'Kortikosteroid'],
        ['CTM 4mg', 5000, 'tablet', 'Antihistamin / alergi'],
        ['Loratadine', 12000, 'tablet', 'Antihistamin'],
        ['Cetirizine', 10000, 'tablet', 'Antihistamin'],
        ['Bisoprolol', 14000, 'tablet', 'Obat hipertensi dan jantung'],
        ['Atorvastatin', 18000, 'tablet', 'Obat kolesterol'],
        ['Simvastatin', 15000, 'tablet', 'Obat kolesterol'],
        ['Furosemide', 8000, 'tablet', 'Obat diuretik'],
        ['Spironolactone', 12000, 'tablet', 'Diuretik hemat kalium'],
        ['Warfarin', 10000, 'tablet', 'Antikoagulan'],
        ['Aspirin 80mg', 5000, 'tablet', 'Pengencer darah'],
        ['Clopidogrel', 20000, 'tablet', 'Anti platelet'],
        ['Digoxin', 12000, 'tablet', 'Obat gagal jantung'],
        ['ISDN', 10000, 'tablet', 'Obat angina pektoris'],
        ['Glimepiride', 10000, 'tablet', 'Obat diabetes'],
        ['Glibenclamide', 8000, 'tablet', 'Obat diabetes'],
        ['Insulin Aspart', 150000, 'botol', 'Insulin kerja cepat'],
        ['Insulin Glargine', 180000, 'botol', 'Insulin kerja panjang'],
        ['Levothyroxine', 10000, 'tablet', 'Obat hipotiroid'],
        ['Propylthiouracil', 12000, 'tablet', 'Obat hipertiroid'],
        ['Albendazole', 15000, 'tablet', 'Obat cacingan'],
        ['Mebendazole', 10000, 'tablet', 'Obat cacingan'],
        ['Diazepam', 8000, 'tablet', 'Obat kecemasan'],
        ['Alprazolam', 12000, 'tablet', 'Obat kecemasan'],
        ['Fluoxetine', 15000, 'kapsul', 'Antidepresan'],
        ['Amitriptyline', 10000, 'tablet', 'Antidepresan'],
        ['Haloperidol', 8000, 'tablet', 'Antipsikotik'],
        ['Chlorpromazine', 10000, 'tablet', 'Antipsikotik'],
        ['Phenytoin', 12000, 'tablet', 'Obat epilepsi'],
        ['Carbamazepine', 15000, 'tablet', 'Obat epilepsi'],
        ['Sodium Valproate', 18000, 'tablet', 'Obat epilepsi'],
        ['Vitamin B Complex', 8000, 'tablet', 'Suplemen vitamin B'],
        ['Vitamin C 500mg', 10000, 'tablet', 'Suplemen vitamin C'],
        ['Vitamin D 400IU', 12000, 'tablet', 'Suplemen vitamin D'],
        ['Vitamin E 400IU', 15000, 'kapsul', 'Suplemen vitamin E'],
        ['Calcium Carbonate', 10000, 'tablet', 'Suplemen kalsium'],
        ['Ferrous Sulfate', 8000, 'tablet', 'Suplemen zat besi'],
        ['Folic Acid', 5000, 'tablet', 'Suplemen asam folat'],
        ['Zinc Sulfate', 8000, 'tablet', 'Suplemen zinc'],
        ['Lansoprazole', 18000, 'kapsul', 'Obat maag'],
        ['Esomeprazole', 20000, 'tablet', 'Obat maag'],
        ['Sucralfate', 15000, 'tablet', 'Pelindung lambung'],
        ['Bisacodyl', 8000, 'tablet', 'Obat sembelit'],
        ['Lactulose', 25000, 'botol', 'Obat sembelit cair'],
        ['Loperamide', 10000, 'tablet', 'Obat diare'],
        ['Kaolin Pectin', 15000, 'botol', 'Obat diare cair'],
        ['Dimenhydrinate', 8000, 'tablet', 'Obat mabuk perjalanan'],
        ['Methylprednisolone', 12000, 'tablet', 'Kortikosteroid'],
        ['Hydrocortisone Cream', 25000, 'tube', 'Krim anti radang kulit'],
        ['Betamethasone Cream', 30000, 'tube', 'Krim kortikosteroid'],
        ['Miconazole Cream', 20000, 'tube', 'Krim anti jamur'],
        ['Clotrimazole Cream', 15000, 'tube', 'Krim anti jamur'],
        ['Ketoconazole Cream', 25000, 'tube', 'Krim anti jamur'],
        ['Acyclovir Cream', 30000, 'tube', 'Krim anti virus herpes'],
        ['Neomycin Ointment', 15000, 'tube', 'Salep antibiotik'],
        ['Gentamicin Ointment', 15000, 'tube', 'Salep antibiotik'],
        ['Silver Sulfadiazine', 35000, 'tube', 'Salep luka bakar'],
        ['Salep 88', 10000, 'tube', 'Salep biang keringat'],
        ['Pengental Darah', 8000, 'tablet', 'Obat wasir'],
        ['Dextromethorphan', 18000, 'tablet', 'Obat batuk kering'],
        ['Guaifenesin', 12000, 'tablet', 'Obat batuk berdahak'],
        ['Bromhexine', 10000, 'tablet', 'Pengencer dahak'],
        ['Ambroxol', 12000, 'tablet', 'Pengencer dahak'],
        ['Pseudoephedrine', 10000, 'tablet', 'Dekongestan hidung'],
        ['Chlorpheniramine', 6000, 'tablet', 'Antihistamin batuk pilek'],
        ['Zinc + Vitamin C', 15000, 'tablet', 'Suplemen imun tubuh'],
        ['Madu Murni 250ml', 50000, 'botol', 'Suplemen kesehatan'],
        ['Curcumin 500mg', 25000, 'kapsul', 'Suplemen anti inflamasi'],
        ['Propolis 10ml', 35000, 'botol', 'Suplemen tetes'],
        ['Omega 3 1000mg', 30000, 'kapsul', 'Suplemen minyak ikan'],
        ['Glucosamine 500mg', 35000, 'tablet', 'Suplemen sendi'],
        ['Meloxicam', 12000, 'tablet', 'Anti inflamasi sendi'],
        ['Allopurinol', 10000, 'tablet', 'Obat asam urat'],
        ['Colchicine', 8000, 'tablet', 'Obat asam urat akut'],
        ['Natrium Diklofenak', 10000, 'tablet', 'Anti nyeri sendi'],
        ['Mefenamic Acid', 10000, 'tablet', 'Anti nyeri'],
        ['Ketorolac', 15000, 'tablet', 'Anti nyeri kuat'],
        ['Tramadol', 25000, 'kapsul', 'Analgesik opioid'],
        ['Paracetamol Sirup 60ml', 20000, 'botol', 'Obat demam anak'],
        ['Amoxicillin Sirup 60ml', 25000, 'botol', 'Antibiotik anak'],
        ['Antasida Sirup 100ml', 18000, 'botol', 'Obat maag anak'],
        ['CTM Sirup 60ml', 15000, 'botol', 'Antihistamin anak'],
        ['Salep Sunburn', 20000, 'tube', 'Obat luka bakar ringan'],
        ['Obat Kumur 250ml', 25000, 'botol', 'Antiseptik mulut'],
        ['Minyak Kayu Putih 30ml', 15000, 'botol', 'Minyak aromaterapi'],
        ['Betadine Solution 30ml', 20000, 'botol', 'Antiseptik luka'],
        ['Oxymetazoline Spray', 25000, 'botol', 'Semprot hidung tersumbat'],
        ['Kalpanak Cream', 30000, 'tube', 'Krim luka diabetes'],
    ];

    public function definition(): array
    {
        $data = self::$obatList[self::$index % count(self::$obatList)];
        self::$index++;
        return [
            'nama_obat' => $data[0],
            'harga' => $data[1],
            'satuan' => $data[2],
            'keterangan' => $data[3],
        ];
    }
}
